services:
  backend:
    build: ./smart-expensive-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://devuserai:passer123@cluster-expensive.lingsbj.mongodb.net/?appName=Cluster-expensive
      - PORT=5000
      - JWT_SECRET=supersecretkey
    restart: unless-stopped

  frontend:
    build: ./smart-expensive-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped